### ISSUE TITLE
If the request is JSON, we need to change the Content-Type

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_sec_tester#6]
https://github.com/luckyframework/lucky_sec_tester/blob/205dcc0e7e1ebfa9548219077c95121e8a5bf795/src/lucky_sec_tester.cr#L42

I wonder if there's a way we can tell what it should be based on the Action :thinking: 

Maybe to start, we just make an extra arg that passes headers... Then you would do

```crystal
scanner.build_target(Api::SignIns::Create, content_type: "application/json")
```

**Comment by bararchy** [comment]
yeha that makes sense! we can open up the API as much as needed if we see there is a usecase. the base sec_tester allows full header set for both request, response and also other things, but not all needed for the wrapper
